# Generated by Django 4.2.3 on 2023-10-15 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image', models.TextField(default='Image Field')),
                ('price', models.PositiveIntegerField()),
                ('hasSub', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about', models.TextField()),
                ('dimension', models.CharField(max_length=256)),
                ('weight', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product')),
            ],
        ),
    ]
