# Generated by Django 4.2.3 on 2023-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.TextField(default='Test Image'),
        ),
    ]
