# Generated by Django 4.2.3 on 2023-10-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_image_subproduct_delete_images_image_sub_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproduct',
            old_name='color',
            new_name='sub_quality',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sub_product',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='subproduct',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default='efcb31c4-c456-491e-af5d-6afaa5444cde', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='inventory.product'),
        ),
    ]
